services:
  postgres:
    image: postgres:16
    container_name: q2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: setubid
    ports:
      - "5433:5432"
    volumes:
      - q2_pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  q2_pgdata: